title: "Правила поведения в сообществах"
description: "Описание правил поведения в сообществах METADATA."

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

author:
  name: "Kitsune Solar"
  email: "kitsune.solar@gmail.com"
  github: "metacraft"
  twitter: "metadatafdn"
